server:
  address: 0.0.0.0
  port: 8083


services:
  users:
    url: http://localhost:8082
  listings:
    url: http://localhost:8081

spring:
  datasource:
    url: "jdbc:h2:mem:test"
    username: "test"
    password: "test"
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
